general.import = [
    "~/.config/alacritty/themes/themes/solarized_osaka.toml"
]

[font]
normal={ family="FiraCode Nerd Font" }
size=14

[window]
option_as_alt="Both"

[colors]
draw_bold_text_with_bright_colors= true

[selection]
save_to_clipboard = true
