add_newline = false

[character]
success_symbol = "[→](#53AFBC)"
error_symbol = "[→](red)"

[directory]
truncate_to_repo = false
style = "#C678DD"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "yellow"

[username]
format = "[|](cyan)[$user]($style)[|](cyan) "
show_always = true

